### ISSUE TITLE
angularjs-google-maps was not injected in your file. When using with grunt.

### ISSUE THREAD

**Issue by gintsgints** [jvandemo/angularjs-google-maps#1]
Probably you need main section in bower.json file to tell which files should be injected into index.html

**Comment by gintsgints** [comment]
Sergeyse: after bower install correct bower.json file, by adding section main, which tells what file should be added index.html

**Comment by jvandemo** [comment]
@gintsgints, @sergeyse: thank you, the main property has been added to bower.json.
