### ISSUE TITLE
Adding custom location to the list of auto complete suggestions.

### ISSUE THREAD

**Issue by nmsbane** [jvandemo/angularjs-google-maps#3]
Hi Jurgen Van de Moere, 

I was going through this SO's question 

http://stackoverflow.com/questions/43316076/add-custom-array-to-google-autocomplete-places-angularjs

i need your suggestion on how to achieve it.

**Comment by jvandemo** [comment]
@nmsbane &mdash; To my knowledge, the Google Places Autocomplete API supports adding custom results to the result list, so I don't think you will be able to accomplish this directly.

As a possible workaround, you would e.g. add 2 inputs to your page:

1. Text input with google maps autocomplete
2. Custom address select dropdown (with prefilled lat/lng)

I will close this issue for now, but feel free to re-open if you feel we could do more to help.

Thanks!!

**Comment by surajaddanki** [comment]
Is there any update on this can we add custom locations to autocomplete suggestions list?

If possible what is the procedure
