### ISSUE TITLE
autocomplete options types are ignored

### ISSUE THREAD

**Issue by mmeeeooowww** [jvandemo/angularjs-google-maps#5]
Setting up the options like so:
```
$scope.autocompleteOptions = {
    types: ['(cities)']
};
```
and passing them in:
```
<input type="text" gm-places-autocomplete="autocompleteOptions" ng-model="autocomplete" />
```

I tried various types to test and they didn't make a difference.

plunkr:
http://plnkr.co/edit/YqC7x67YPrheBwozsdTj?p=preview

**Comment by jvandemo** [comment]
@mmeeeooowww &mdash; Can you please try the following:

```html
<input type="text" gm-places-autocomplete gm-options="autocompleteOptions" ng-model="autocomplete" />
```

and let us know if that works? Thanks! 👍

**Comment by mmeeeooowww** [comment]
@jvandemo That Works! Thanks!
